### ISSUE TITLE
Issue with dereferencing Swagger paths

### ISSUE THREAD

**Issue by natebrunette** [thephpleague/json-guard#10]
When using this with swagger, swagger paths generally starts with a `/` which causes an extra `/` to be added to the dereferencing pointer.  This ultimately leads to the dereferencer never finding the path.

**Comment by yuloh** [comment]
Hi,

Can you post an example schema?

Thanks!

**Comment by natebrunette** [comment]
http://petstore.swagger.io/v2/swagger.json

Although, I just realized this is not a valid json schema v4.  Your dereferencer seems to find $ref fine, though.

**Comment by yuloh** [comment]
Ok, I've reproduced the bug.  It looks like the problem is with the JSON pointer implementation.

Just to make sure I understand the issue, the issue is that any `$ref` that is nested under a property beginning with `/` is not dereferenced right?

I.E this reference will not be resolved:

```json
{
  "item": {
    "key": "value"
  },
  "/slash-item": {"$ref": "#/item"}
}
```

**Comment by natebrunette** [comment]
Right, it will create an array like

```
['', 'slash-item']
```

And will not be able to find `''` in the path

**Comment by yuloh** [comment]
OK, I just pushed a fix to master.  I had neglected to properly escape the forward slash when building the JSON pointer.

I checked the swagger JSON you posted and it de-referenced correctly.  Can you give that a shot and let me know if it works for you?

Thanks!

**Comment by natebrunette** [comment]
It appears to be working.  Is there a particular reason there's a reference "proxy" object in place instead of the resolved object?  Is there a way I can resolve all reference objects?

**Comment by yuloh** [comment]
Are you trying to inline all of the references for documentation or
something?

I plan on adding the ability to do that, but it isn't supported at the
moment. If you try to inline the references a circular reference will cause
an infinite loop. It's only safe to do if you don't have circular
references.

The proxy allows us to resolve as necessary to the depth of the data.  It
also allows re encoding the json, which will just return null otherwise for
circular references.

Here is an explanation: http://mattallan.org/2016/json-schema-references/

For making docs when you don't have circular references, it would be nice
to inline them. I plan on adding an 'inline' method that fully resolves and
throws an exception for circular references.  Is that what you need?

**Comment by natebrunette** [comment]
Ah, that makes a lot of sense.  My personal use case is incorporating this into a library that will deserialize a swagger schema into typesafe PHP objects.  I didn't realize there was a problem with circular references.

You can consider this issue closed, thanks for your quick responses.  Good work on the library, I was writing something similar myself.  I'm glad I don't have to finish it :)

**Comment by natebrunette** [comment]
Do you have an ETA on a new tag?

**Comment by yuloh** [comment]
I just tagged a new version with this fix in it.
