### ISSUE TITLE
Native PHP array support

### ISSUE THREAD

**Issue by HeathNaylor** [thephpleague/json-guard#137]
In the Overview markdown, it is noted that array types are _not_ supported by default.

In my use case, we are working with raw PHP array's to avoid memory bloat as we are operating on a large number of results.

Is there any reason we do not want to provide array support specifically?

**Comment by yuloh** [comment]
This is covered in the FAQ. http://json-guard.thephpleague.com/faq

> If you decoded your json as an array (json_decode($data, true)), an empty object is decoded the same as an empty array; they both decode to []. This would make it impossible to validate “type”: “object” or “type”: “array” when the object/array is empty.

**Comment by HeathNaylor** [comment]
@yuloh so, for our scenario for the time being, would you say that creating our own rule set to operate on the array is the path forward?

**Comment by yuloh** [comment]
You would probably need to change most of the library (and json-reference if using references).

- update all `property_exists` calls to check for a property or an array key
- update `is_object` checks to check for both objects and arrays
- update `is_array` checks to make sure it's an actual JSON array and not an object

You will also need to change the validator because it checks for an object, so just a rule set wouldn't work.
