### ISSUE TITLE
Feature: setting default values, based on schema

### ISSUE THREAD

**Issue by hannesvdvreken** [thephpleague/json-guard#24]
Something I've been missing from json-schema validators is to set the default values.

http://json-schema.org/latest/json-schema-validation.html#anchor101

Is this something you would accept as a PR? If so, what would it look like, ideally, in pseudo code?

**Comment by yuloh** [comment]
I've been doing some research and trying to figure out the best solution.

[This FAQ](http://python-jsonschema.readthedocs.io/en/latest/faq/#why-doesn-t-my-schema-that-has-a-default-property-actually-set-the-default-on-my-instance) from a python validator explains the reason it's difficult to support.  The spec doesn't require that default actually does anything, and it's possible to set a default that doesn't match the schema.

[The official test suite requires](https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/develop/tests/draft4/default.json) that invalid defaults don't cause validation to fail.  If you read [the PR](https://github.com/json-schema-org/JSON-Schema-Test-Suite/pull/67) it sounds like validators shouldn't try to use defaults.

I was thinking about making it possible to add extensions that transform the data, but it's pretty challenging to make defaults work with the validator.

Since the validation rules don't run in a guaranteed order, You would need to set the defaults before you start validating that object.  Otherwise rules like 'required' will say the required property is missing.

The validator only keeps recursing through the properties of the schema [if that property exists in the data](https://github.com/thephpleague/json-guard/blob/master/src/Constraints/Properties.php#L24).  That's normally fine since required is not nested under the property and we don't need to go through those rules if the data doesn't exist.  

```javascript
// data:
{}
// schema:
{
    "type": "object",
    "required": [ // required constraint checks this and reports the error
        "a"
    ],
    "properties": {
        "a": {
            "type": "integer",  // validator will never get to these rules
            "default": 12
        }
    }
}
```

If you were going to set defaults, you would need to check if the object is missing the property and set the default beforehand.  I think this might cause an infinite recursion scenario, since a circular reference with a default would cause the validator to keep trying to set the default forever:

```javascript
//data
{ }
// schema
{
    "type": "object",
    "properties": {
        "a": {
            "type": "object",
            "default": {"$ref": "#"} // keeps trying to set the data to { "a": { "a": {....}}}
        }
}
```

**Comment by hannesvdvreken** [comment]
Thanks for the proper research 👌 !

So the conclusion is ...? I'm fine either way. Just wanted to spawn a little discussion and see what happens. Close this issue if no further action will be taken.

Cheers!

**Comment by yuloh** [comment]
I don't think it should be part of the validator itself, for the reasons mentioned above.  I think this could be really useful as a separate library though.

I'm going to leave this issue open until I update the docs to explain why the validator doesn't use defaults.
