### ISSUE TITLE
Missing Required field is not represented in the ValidationError object

### ISSUE THREAD

**Issue by philcldn** [thephpleague/json-guard#32]
Hi,

I've been using JSON-Guard for a few days in a new project. As I've been building and testing my schemas I've found that the [Required](https://github.com/thephpleague/json-guard/blob/master/src/Constraints/Required.php) Property Constraint doesn't return the fields which are missing in the [ValidationError](https://github.com/thephpleague/json-guard/blob/master/src/ValidationError.php) object.

The array_diff has already been done, so the data is there. I'm having to re-traverse the tree and do my own diff to get the missing fields.

It would make sense to _me_ to pass those values (with `array_values()` possibly) to the `$value` parameter of ValidationError object. But I understand there was probably a design decision around why that object is that way so haven't created a PR to do that yet.

I've not found any other Constraints that exhibit this or similar behaviour, but I'll update this issue if I find any.

Happy to provide code examples if needed.

Thanks,

**Comment by yuloh** [comment]
Hm, good point.

Right now the error returns the value that failed and any constraints.  For required the constraint is the list of required properties, and the value is the entire object (before diffing).  We always return the entire value so you know why the data failed.

As you pointed out, we aren't returning the result we get from comparing the value to the constraint.  I don't think many constraints actually calculate something.  The closest I can think of is min/max length where we calculate the actual length of the string.

It would make sense to add the calculation that caused the failure to the error so that you don't need to redo it when localizing error messages.  I'm not sure what to call the field yet.

In the meantime, this should work to get the missing fields without re-traversing the JSON object:

```php
$missing = array_values(array_diff($error->getConstraints()['required'], array_keys(get_object_vars($error->getValue()))));
```
