### ISSUE TITLE
Best way to validate an array?

### ISSUE THREAD

**Issue by belohlavek** [thephpleague/json-guard#34]
I want to validate incoming requests to my API against an specific schema. In Laravel/Lumen, the request parameters are made available as an array. So I have a multidimensional array of values, but json-guard only validates objects, so I find myself using this ugly trick to get it to work:

```
$object = json_decode(json_encode($array));
$validator = new League\JsonGuard\Validator($object, $schema);
```

**The question:** is there a better (cleaner) way to get around this?
_Just to clarify: type-casting only works on the top level array._

**Edit:**
I just found out I can get the request body as a string containing json, which kinda solves the ugliness mentioned above. I will leave this opened because I'm curious about how other people would have handled this problem :smile:

**Comment by yuloh** [comment]
Hello,

JSON Guard only works with objects, because some validations are impossible to do with an array.  I just [added a FAQ](http://json-guard.thephpleague.com/faq/) that explains why.

With Laravel/Lumen/Symfony I'm pretty sure you can use [`getContent()`](https://github.com/symfony/http-foundation/blob/master/Request.php#L1504) to get the raw request body.  This should work:

```php
$object = json_decode(app('request')->getContent());
```

**Comment by belohlavek** [comment]
Yes, I just found out about getContent()! :sweat_smile: 
Thanks for the link and great work!
