### ISSUE TITLE
Property with name `$ref` is considered a reference and swagger specs are not validated

### ISSUE THREAD

**Issue by ribeiropaulor** [thephpleague/json-guard#37]
Swagger Specification v 2.0 defines a `$ref` property. Json Guard consider it a reference. It's not.

How to reproduce.

composer.json

```
{
    "require": {
        "league/json-guard": "^0.3.2",
        "symfony/yaml": "^3.1"
    }
}
```

PHP Testing code:
```
<?php

include __DIR__ . '/vendor/autoload.php';

$deref  = new League\JsonGuard\Dereferencer();
$schema = $deref->dereference(
    'https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v2.0/schema.json#'
);

// all below should validate successfully
// all are taken from https://rebilly.github.io/ReDoc/
$specs = [
    'https://rebilly.github.io/ReDoc/swagger.yaml',
    'https://api.apis.guru/v2/specs/instagram.com/1.0.0/swagger.yaml',
    'https://api.apis.guru/v2/specs/googleapis.com/calendar/v3/swagger.yaml',
    'https://api.apis.guru/v2/specs/data2crm.com/1/swagger.yaml',
    'https://api.apis.guru/v2/specs/graphhopper.com/1.0/swagger.yaml'
];
$allValid = true;
foreach ($specs as $spec) {
    $data      = \Symfony\Component\Yaml\Yaml::parse(file_get_contents($spec));
    $data      = json_decode(json_encode($data));
    $validator = new League\JsonGuard\Validator($data, $schema);

    if ($validator->fails()) {
        echo "Swagger Specification `{$spec}` is not valid.\n";
        /** @var \League\JsonGuard\ValidationError $error */
        foreach ($validator->errors() as $error) {
            echo sprintf(" - [%s] (%s) %s\n", $error->getPointer(), $error->getCode(), $error->getMessage());
        }
        $allValid = false;
    }
}
if ($allValid) {
    echo "All Swagger Specifications are valid.\n\n";
}

```
The code above should run without problems. Swagger spec is well known and those specs are valid. You can test them on http://bigstickcarpet.com/swagger-parser/www/index.html .

At first I tried to change the line 176 of `League\JsonGuard\Dereferencer` from

`if ($this->isRef($attribute)) {`

to

`if ($this->isRef($attribute) && is_string($parameter)) {`

which I think is the correct way to go. Then I started getting an `InvalidArgumentException` with message `Invalid JSON: Syntax error` at `/vendor/league/json-guard/src/functions.php:18`.

**Comment by yuloh** [comment]
Hi,

Thanks for the reproduction steps.  What is the error you are actually experiencing, and what do you expect to happen?

I get this error if I just try to dereference the schema:

```
preg_match() expects parameter 2 to be string, object given
```

Is that what you are seeing?

> to `if ($this->isRef($attribute) && is_string($parameter)) {` which I think is the correct way to go.

I think you are on the right track.  The `$ref` is defined [by this spec](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03), which says:

> A JSON Reference is a JSON object, which contains a member named
   "$ref", which has a JSON string value.

> If a JSON value does not have these characteristics, then it SHOULD
   NOT be interpreted as a JSON Reference.

So yeah, we do need to check that it's a string.

I think the problem is because that swagger schema has this:

```json
"properties": {
        "$ref": {
          "type": "string"
        }
}
```

It would probably be better to change the `isRef` function to something like `isRef($property, $value)` and do the is_string check there.
