### ISSUE TITLE
Validating against json hyperschemas

### ISSUE THREAD

**Issue by madhavsuresh** [thephpleague/json-guard#46]
Hi All,

I am very new to json schemas, I apologize if this question doesn't make much sense.

Can json-guard validate against endpoints I define in the links section of a hyper-schema? For example, if I am creating my schema to conform to this: https://github.com/interagent/prmd, my api endpoints will be defined in the "links" section. How can I use json-guard in this situation?

Madhav

**Comment by yuloh** [comment]
Hi,

If you look at the [JSON Schema documentation](http://json-schema.org/documentation.html), there are 3 specs.  JSON Guard only implements the validation specification.  It doesn't really know anything about the hyper schema spec.  You can still use it for validating a hyper-schema api though.

 Stealing an example from [this article](https://brandur.org/elegant-apis), the endpoint has it's schema listed under the schema keyword.

```json
{
  "description": "Create a new app.",
  "href": "/apps",
  "method": "POST",
  "rel": "create",
  "schema": {
    "properties": {
      "name": {
        "$ref": "#/definitions/app/definitions/name"
       }
     },
     "required": ["name"],
     "type": "object"
  },
  "title": "Create"
}
```

That schema is a regular JSON Schema, which means JSON Guard can use it to validate.  To use that schema with JSON Guard, you can either load the entire hyper schema and use a pointer:

```php
// we added a pointer (#/schema) so that we only use the part under the schema property.
$deref->dereference('http://localhost:8000/hyper-schema.json#/schema');
```

...or have your hyper-schema reference separate files for the schema, and just load those:

```json
{
  "description": "Create a new app.",
  "href": "/apps",
  "method": "POST",
  "rel": "create",
  "schema": {
      "$ref": "some-other-file.json"
  },
  "title"
}
```

```php
$deref->dereference('http://localhost:8000/some-other-file.json');
```

Using separate files is nice since you don't need to use pointers or load the entire hyper-schema into memory.

Hopefully that helps, let me know if you have any more questions.

**Comment by madhavsuresh** [comment]
Awesome thanks, that does help.
