### ISSUE TITLE
$ref: relative schema files aren't resolved

### ISSUE THREAD

**Issue by stuartherbert** [thephpleague/json-guard#49]
Given this schema saved as 'watch-list.v1.json':

```
{
    "$schema": "http://json-schema.org/schema#",
    "id": "http://example.com/schemas/etl/watch-list.v1.json",
    "type": "array",
    "items": [
        { "$ref": "watch-for.v1.json" }
    ],
    "minItems": 1
}
```

... and this code:

```
$dereferencer = new Dereferencer;
$schema = $dereferencer->dereference("file://" . realpath(__DIR__ . '/../public/schemas/json-guard-bugs/relative-schema-files/watch-list.v1.json'));
$validator = new JsonSchemaValidator($etl, $schema);
```

... this exception is thrown:

```
PHP Fatal error:  Uncaught League\JsonGuard\Exceptions\SchemaLoadingException: The schema "http://example.com/schemas/etl/watch-list.v1.jsonwatch-for.v1.json" could not be loaded
```

The problem is that the Dereferencer isn't generating a correct URI for the relative file 'watch-for.v1.json'.
- it shouldn't be switching schemes from (the implicit) 'file' to 'http'
- it shouldn't be appending 'watch-for.v1.json' onto the end of the 'id' property like that :)

**Comment by yuloh** [comment]
> it shouldn't be switching schemes from (the implicit) 'file' to 'http'

I'm pretty sure having an absolute ID requires the validator to start using your ID as the resolution scope.  Since your id uses http, it will switch to http.

Initially the scope is the URI of the file, so it should be using `file://`:

> The initial resolution scope of a schema is the URI of the schema itself, if any, or the empty URI if the schema was not loaded from a URI.

([from here](http://json-schema.org/latest/json-schema-core.html#anchor26))

...but your id alters the resolution scope, [like in this example](http://json-schema.org/latest/json-schema-core.html#anchor27).  So once the ID is encountered, the validator will start using that as the resolution scope and switch to `http://` (like the example for `some://where.else/completely#`).

> it shouldn't be appending 'watch-for.v1.json' onto the end of the 'id' property like that :)

That definitely looks like a bug.  A PR is appreciated since I will be traveling for the next week and probably won't have a chance to get to this.

**Comment by yuloh** [comment]
I pushed a failing test for the filename bug:

https://github.com/thephpleague/json-guard/compare/master...yuloh:absolute-id-filename-error?expand=1

**Comment by yuloh** [comment]
Hi,

I pushed a fix for the URI resolution to the master branch.  Please give it a try and let me know if it works for you.

Thanks!

**Comment by yuloh** [comment]
I'm going to close this. Feel free to reopen it if you are still having issues.
