### ISSUE TITLE
Insufficient DateTime-Validation

### ISSUE THREAD

**Issue by fcool** [thephpleague/json-guard#77]
The `DATE_TIME_PATTERN` of the "Format" validator accepts dates which afterwards are not usable by the `DateTime::__construct()`.

https://github.com/thephpleague/json-guard/blob/master/src/Constraints/Format.php#L14

For example the expression matches:
9999-99-9999999999

which is obviously no date. 

9999-99-99 

would be arguable, but month and day are definitively... well... ;) Nevertheless: Its accepted.

I'm not sure what the intend of this expression has been. But for us this has caused some trouble.

Could you imagine to use this expression instead? (It is not perfect either, but close ;) )

http://stackoverflow.com/a/28022901

**Comment by yuloh** [comment]
Hello,

> I'm not sure what the intend of this expression has been

The regex should validate that the date is a valid [RFC 3339](https://tools.ietf.org/html/rfc3339) date/time format string.  It's defined by JSON Schema [here](http://json-schema.org/latest/json-schema-validation.html#rfc.section.7.3.1).

We can't use the regex you linked to because that allows all of ISO8601, which will cause [this test](https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/develop/tests/draft4/optional/format.json#L17) to fail.

I will take a look when I have a chance and see what the RFC says about valid ranges.  That definitely seems wrong.

**Comment by fcool** [comment]
Great! ;)

Indeed, as every RFC 3339 should be of ISO8601, too. (But not vice versa, correct)

**Comment by yuloh** [comment]
Yeah, that's not good.

I pushed an improved regex [over here](https://github.com/yuloh/json-guard/tree/better-date-time-regex).  It seems to catch all of the cases you mentioned.  Can you take a look?

**Comment by yuloh** [comment]
I merged the improved regex to master. Please reopen the issue if your find any cases that are handled incorrectly.
